import type { Linter } from 'eslint';

/**
 * react rules, ported 1:1 from the upstream effective config (reference/upstream-effective-rules.txt).
 * Ids that changed between plugin majors are listed in rule-renames.ts.
 */
export const reactRules: Linter.RulesRecord = {
  'react/jsx-indent': ['error', 2],
  'react/jsx-indent-props': ['error', 2],
  'react/function-component-definition': [
    'warn',
    { namedComponents: 'arrow-function', unnamedComponents: 'arrow-function' },
  ],
  'react/button-has-type': 'warn',
  'react/hook-use-state': 'warn',
  'react/jsx-boolean-value': 'warn',
  'react/jsx-fragments': 'warn',
  'react/jsx-no-leaked-render': 'warn',
  'react/jsx-no-target-blank': ['error', { allowReferrer: true, links: true, forms: false }],
  'react/jsx-no-useless-fragment': ['warn', { allowExpressions: true }],
  'react/jsx-pascal-case': 'warn',
  'react/jsx-sort-props': [
    'warn',
    { callbacksLast: true, shorthandFirst: true, multiline: 'last', noSortAlphabetically: true, locale: 'auto' },
  ],
  'react/no-array-index-key': 'warn',
  'react/no-unstable-nested-components': 'error',
  'react/self-closing-comp': 'warn',
  'react/no-access-state-in-setstate': 'warn',
  'react/no-arrow-function-lifecycle': 'error',
  'react/no-deprecated': 'error',
  'react/no-did-update-set-state': 'error',
  'react/no-direct-mutation-state': 'error',
  'react/no-find-dom-node': 'error',
  'react/no-invalid-html-attribute': 'error',
  'react/no-is-mounted': 'error',
  'react/no-namespace': 'error',
  'react/no-redundant-should-component-update': 'error',
  'react/no-render-return-value': 'error',
  'react/no-unsafe': 'error',
  'react/no-unused-prop-types': 'error',
  'react/no-unused-state': 'error',
  'react/jsx-closing-tag-location': 'error',
  'react/jsx-curly-newline': ['error', { multiline: 'consistent', singleline: 'forbid' }],
  'react/jsx-curly-spacing': ['error', 'never'],
  'react/jsx-equals-spacing': ['error', 'never'],
  'react/jsx-first-prop-new-line': 'error',
  'react/jsx-key': ['error', { checkFragmentShorthand: true, checkKeyMustBeforeSpread: true, warnOnDuplicates: true }],
  'react/jsx-max-props-per-line': ['error', { maximum: 3, when: 'multiline' }],
  'react/jsx-no-bind': [
    'error',
    {
      allowArrowFunctions: true,
      allowBind: false,
      allowFunctions: false,
      ignoreRefs: false,
      ignoreDOMComponents: false,
    },
  ],
  'react/jsx-no-duplicate-props': ['error', { ignoreCase: true }],
  'react/jsx-no-undef': 'error',
  'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never', propElementValues: 'always' }],
  'react/jsx-props-no-multi-spaces': 'error',
  'react/jsx-tag-spacing': [
    'error',
    { closingSlash: 'never', beforeSelfClosing: 'always', afterOpening: 'never', beforeClosing: 'never' },
  ],
  'react/jsx-wrap-multilines': [
    'error',
    {
      declaration: 'parens-new-line',
      assignment: 'parens-new-line',
      return: 'parens-new-line',
      arrow: 'parens-new-line',
      condition: 'ignore',
      logical: 'ignore',
      prop: 'ignore',
    },
  ],
  'react-hooks/rules-of-hooks': 'error',
  'react/display-name': 'error',
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-uses-react': 'error',
  'react/jsx-uses-vars': 'error',
  'react/no-children-prop': 'error',
  'react/no-danger-with-children': 'error',
  'react/no-string-refs': 'error',
  'react/no-unescaped-entities': 'error',
  'react/no-unknown-property': 'error',
  'react/require-render-return': 'error',
};
