import type { Linter } from 'eslint';

/**
 * core rules, ported 1:1 from the upstream effective config (reference/upstream-effective-rules.txt).
 * Ids that changed between plugin majors are listed in rule-renames.ts.
 */
export const coreRules: Linter.RulesRecord = {
  'no-console': ['warn', { allow: ['warn', 'error'] }],
  'no-var': 'error',
  'prefer-const': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  camelcase: [
    'error',
    {
      allow: ['^UNSAFE_'],
      ignoreDestructuring: false,
      properties: 'never',
      ignoreImports: false,
      ignoreGlobals: false,
    },
  ],
  'func-names': ['error', 'as-needed'],
  'new-cap': ['error', { capIsNew: false, newIsCap: true, properties: true }],
  'no-bitwise': 'error',
  'no-lonely-if': 'warn',
  'no-multi-assign': 'error',
  'no-unneeded-ternary': 'error',
  'prefer-object-spread': 'warn',
  'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
  'func-name-matching': 'error',
  'newline-before-return': 'error',
  'no-empty': 'error',
  'no-new-object': 'error',
  'no-multi-str': 'error',
  'func-style': ['error', 'expression'],
  'one-var': ['error', 'never'],
  'newline-after-var': ['error', 'always'],
  'operator-assignment': ['error', 'always'],
  'padding-line-between-statements': ['error', { blankLine: 'always', prev: '*', next: 'return' }],
  'spaced-comment': ['error', 'always', { line: { exceptions: ['-', '+', '/'], markers: ['=', '!', '/'] } }],
  'no-await-in-loop': 'error',
  'no-constant-binary-expression': 'error',
  'no-promise-executor-return': 'error',
  'no-template-curly-in-string': 'error',
  'no-unreachable-loop': 'error',
  'no-useless-computed-key': 'warn',
  'no-useless-rename': 'error',
  'object-shorthand': 'error',
  'prefer-numeric-literals': 'error',
  'prefer-template': 'error',
  'symbol-description': 'error',
  'prefer-destructuring': [
    'error',
    { VariableDeclarator: { array: false, object: true }, AssignmentExpression: { array: true, object: false } },
    { enforceForRenamedProperties: false },
  ],
  'prefer-exponentiation-operator': 'error',
  'no-duplicate-imports': 'error',
  'array-callback-return': ['error', { allowImplicit: true, checkForEach: false, allowVoid: false }],
  'block-scoped-var': 'error',
  'default-case-last': 'error',
  eqeqeq: 'error',
  'grouped-accessor-pairs': 'error',
  'no-alert': 'error',
  'no-caller': 'error',
  'no-constructor-return': 'error',
  'no-else-return': ['error', { allowElseIf: false }],
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-implicit-coercion': [
    'error',
    { boolean: false, number: true, string: true, allow: [], disallowTemplateShorthand: false },
  ],
  'no-iterator': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': [
    'error',
    {
      props: true,
      ignorePropertyModificationsFor: ['acc', 'accumulator', 'e', 'req', 'request', 'res', 'staticContext'],
    },
  ],
  'no-proto': 'error',
  'no-return-assign': 'error',
  'no-return-await': 'error',
  'no-script-url': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-useless-call': 'error',
  'no-useless-concat': 'error',
  'no-useless-return': 'warn',
  'prefer-regex-literals': 'error',
  yoda: ['error', 'never', { exceptRange: true, onlyEquality: false }],
  'accessor-pairs': 'error',
  'consistent-return': 'error',
  'no-global-assign': 'error',
  'no-invalid-this': 'error',
  'no-loop-func': 'error',
  'no-void': 'error',
  'no-unused-expressions': 'error',
  'no-with': 'error',
  'require-atomic-updates': 'error',
  'default-case': ['error', { commentPattern: '^no default$' }],
  'max-classes-per-file': ['error', 1],
  'guard-for-in': 'error',
  'no-magic-numbers': [
    'error',
    {
      ignore: [0, 1],
      ignoreDefaultValues: true,
      ignoreArrayIndexes: true,
      enforceConst: true,
      detectObjects: false,
      ignoreClassFieldInitialValues: false,
    },
  ],
  'no-restricted-properties': [
    'error',
    { object: 'arguments', property: 'callee', message: 'arguments.callee is deprecated' },
    { object: 'global', property: 'isFinite', message: 'Please use Number.isFinite instead' },
    { object: 'self', property: 'isFinite', message: 'Please use Number.isFinite instead' },
    { object: 'window', property: 'isFinite', message: 'Please use Number.isFinite instead' },
    { object: 'global', property: 'isNaN', message: 'Please use Number.isNaN instead' },
    { object: 'self', property: 'isNaN', message: 'Please use Number.isNaN instead' },
    { object: 'window', property: 'isNaN', message: 'Please use Number.isNaN instead' },
  ],
  'no-label-var': 'error',
  complexity: ['error', 20],
  'for-direction': 'error',
  'no-async-promise-executor': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-else-if': 'error',
  'no-duplicate-case': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-misleading-character-class': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-octal': 'error',
  'no-prototype-builtins': 'error',
  'no-regex-spaces': 'error',
  'no-self-assign': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-labels': 'error',
  'no-useless-backreference': 'error',
  'no-useless-catch': 'error',
  'no-useless-escape': 'error',
  'require-yield': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
};
